### ISSUE TITLE
Standard Target Group not showing all buffs

### ISSUE THREAD

**Issue by Revanbane** [Tojaso/Raven#2]
Hello,
first of all thank you so much for continuing development of Raven, it's the best buff addon by far.

I was setting up a new UI and used standard groups. Having a problem with Target group not displaying all desired buffs, no idea why. For instance, no mount buffs are displayed while other categories are working properly.

https://i.imgur.com/EevWOT2.png
https://i.imgur.com/3Mm50Rn.png
https://i.imgur.com/E2xnBKY.png

Not sure if I'm missing something or if this is unintended behaviour.

Thanks!

**Comment by Tojaso** [comment]
The Target bar group by default does not include long term buffs. You can enable them on its Timer Options tab. The default was set that way since it was mostly expected to support monitoring enemies in combat.

**Comment by Tojaso** [comment]
By default the Target bar group only includes the buffs and debuffs cast by the player, not those cast on the target by others.

In addition, by default, the Target bar group does not show long term buffs and debuffs. This can be changed on its Timer Options tab.

**Comment by Revanbane** [comment]
Thank you, couldn't figure it out!
