### ISSUE TITLE
Buffs not showing on enemy target

### ISSUE THREAD

**Issue by cyanophage** [Tojaso/Raven#6]
I would like to show a bar that has buffs on the enemy target. Things like when an enemy casts a Renew, or a Fire Shield.
I made a new Auto Group,
In the Bar Groups tab I set:
General - I enabled the group and set "show when" to all the time by ticking every box.
Buffs - I ticked "Enable Auto buffs", "Action On" = "Target", "Exclude on" nothing, "Cast by" = "Anyone", "include by type" nothing.

With these settings I don't see buffs on the enemy target and the function DetectNewBuffs in Bars.lua does not get called. However if I change "Action On" to "Player" then I can see buffs on me just fine and that function is called. I feel like this is a bug. 

I am playing in Classic

**Comment by Tojaso** [comment]
I think this is because Raven is calling an entry point in LibClassicDurations that doesn’t support enemy buffs. It looks like there is an alternate entry point that should fix this. I will test it in the next few days and see if that takes care of the issue. Thank you for reporting this!

**Comment by cyanophage** [comment]
I had a play around changing some things in LCD and couldn't get enemy buffs to show. Did you have any better luck getting it to work?

**Comment by Tojaso** [comment]
I have a test version but I am having trouble testing it since my characters on classic are low level. If I can't verify this version one way or the other in next two days then I will build a beta that you can try.

**Comment by cyanophage** [comment]
If you push to a dev branch or upload a zip somewhere I can test it for you and let you know how it's going. 
Also I think that you can test it by doing a duel with someone and then they become the "enemy"

**Comment by Tojaso** [comment]
The r535 beta has a change in it that supposedly addresses enemy buffs on classic. You will need to enable out-of-date addons for classic servers since I did not build the classic-specific version yet (which only differs in TOC files).

I still need to do more testing on both classic and retail before release. I appreciate you testing specifically for enemy buffs as well. I am hopeful given the changes in newest version of LibClassicDurations but not extremely confident. I don't have any other ideas for how to solve this issue at this time so fingers are crossed.

**Comment by cyanophage** [comment]
I tested your update on some mobs in STV and was able to see the buffs! Thanks!

I was just looking at the code for ShadowedUnitFrames. They have a thing in the changelog that says they made changes to show enemy buffs for classic. There is a part where they do a bit of a hack to make it work for enemy buffs. 

```
-- LibClassicDurations only fires for target, and various nameplate units we don't support.
-- so we hardcode in the unit check, but it'll always effectively be target and no other SUF unit frames.
if( frame.unit == "target" and ShadowUF.db.profile.units[frame.unitType].auras.buffs.approximateEnemyData ) then
	frame.auras.auraFunc = LibClassicDurations.UnitAuraDirect
	LibClassicDurations.RegisterCallback(frame, "UNIT_BUFF", function(event, unit)
		if( frame.unit == unit ) then
			Auras:Update(frame)
		end
	end)
else
	frame.auras.auraFunc = UnitAura
end
```

**Comment by Tojaso** [comment]
Glad to hear that it is working for you! I will continue testing and then release a version with classic TOC when ready. Unless something shows up, I will close this issue when the release is official.
